version: '3.9'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=usertest222

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dbtest
      - DB_USER=usertest
      - DB_PASS=usertest222
    depends_on:
      - db